### PR TITLE
Last minute changes

### PR DESCRIPTION
**Pull request by AmGthrow**
- Improves placeholder text in Analytics screen
- Rewords "salary" and "revenue" to "earnings"
- Rewords "fuel cost" to "expenses"

image
image

### CODE REVIEW

**Comment by miruntheworld** [comment]
image
image
image
image
- since i've added the logo on the images themselves, i deleted the image composable for the logo and restructured WelcomeScreen.kt a bit

**Comment by miruntheworld** [comment]
image
image

- i removed the arrow to make an image composable for the arrow such that it aligns with the text "Driving mode is off. Turn on?" output should be like this
image

**Comment by miruntheworld** [comment]
image
this adds background to the app icon since jeepni was not that visible on the phone I used yesterday

image
same goes here. image for custom alarm was not visible if dark mode

**Comment by miruntheworld** [comment]
image

**Comment by Oethir** [comment]
centered the content of the cards 
Screenshot_20230612_182323_JeepNi

**Pull request merged**
